repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-added-large-files
        exclude: (site)

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        name: Cleanup imports
        args:
          - --in-place
          - --remove-all-unused-imports
          - --expand-star-imports
          - --ignore-init-module-imports

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.7.0
    hooks:
      - id: isort
        name: Sorts imports
        args: [
            # Align isort with black formatting
            "--multi-line=3",
            "--trailing-comma",
            "--force-grid-wrap=0",
            "--use-parentheses",
            "--line-width=99",
          ]

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        name: Fixes formatting
        language_version: python3
        args: ["--line-length=99"]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: Checks pep8 style
        args:
          - --max-line-length=99
          # F405 - init imports * from module
          # F401 - ignore imports used in init
          # F403 - import * used in init
          - --exclude=__init__.py
          # ignore long comments (E501), as long lines are formatted by black
          # ignore Whitespace before ':' (E203)
          # ignore Line break occurred before a binary operator (W503)
          # ignore module level import not at top of file (E402) to skip tests with uninstalled modules (pytest.importorskip)
          - --ignore=E501,E203,W503,E402

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: dmypy
        files: \.py$
        # pre-commit send full file list so exclude in .mypy.ini is ignored
        exclude: (tests)
        language: python
        require_serial: true
        args: ["run", "--", "--strict", "--implicit-reexport", "--warn-unused-ignores", "--cache-fine-grained", "--no-namespace-packages"]

      - id: pylint
        name: Pylint
        entry: pylint --max-line-length=99 --ignore-imports=yes
        files: \.py$
        exclude: (tests|version.py|setup.py)
        language: python

      - id: pydocstyle
        name: docstrings
        entry: pydocstyle
        language: python
        exclude: (tests|version.py)
        args:
          - --ignore=D100,D203,D405,D407,D213,D413
